# Generated by Django 5.2.6 on 2025-11-17 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_management_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guidereviewrequest',
            name='applicant',
            field=models.OneToOneField(help_text='The user requesting guide status.', on_delete=django.db.models.deletion.CASCADE, related_name='guide_review_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidereviewrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_reviews_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemalert',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='If set, this alert is only for this specific user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
