# Generated by Django 5.2.6 on 2025-09-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Cultural', 'Cultural'), ('Historical', 'Historical'), ('Adventure', 'Adventure'), ('Nature', 'Nature')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('average_rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('average_rating', models.FloatField(default=0.0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction', to='destinations_and_attractions.destination')),
            ],
        ),
    ]
