# Generated by Django 5.2.6 on 2025-11-17 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations_and_attractions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The guide who created this destination listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_destinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attraction',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations_and_attractions.destination'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations_and_attractions.destination'),
        ),
    ]
