# Generated by Django 5.2.6 on 2025-11-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_and_attractions', '0003_remove_destination_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary_timeline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
