# Generated by Django 5.2.6 on 2025-11-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_and_attractions', '0004_tourpackage_itinerary_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
