# Generated by Django 5.2.6 on 2026-02-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_and_attractions', '0005_destination_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Historical', 'Historical'), ('Adventure', 'Adventure'), ('Nature', 'Nature'), ('Beaches', 'Beaches'), ('Mountains', 'Mountains'), ('Rivers', 'Rivers'), ('Islands', 'Islands')], max_length=50),
        ),
    ]
