# Generated by Django 5.2.6 on 2026-03-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_and_attractions', '0006_alter_destination_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
