# Generated by Django 5.2.6 on 2026-04-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_and_attractions', '0010_destination_municipality_and_location_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='copied_from',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=20),
        ),
    ]
