# Generated by Django 5.2.6 on 2026-04-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_and_attractions', '0011_tourpackage_copied_from_tourpackage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='copied_from',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='status',
        ),
    ]
