# Generated by Django 5.2.6 on 2025-11-13 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='host',
            field=models.ForeignKey(limit_choices_to={'guide_approved': True, 'is_local_guide': True}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodation_booking.accommodation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(blank=True, limit_choices_to={'guide_approved': True, 'is_local_guide': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_tours_booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='tourist',
            field=models.ForeignKey(limit_choices_to={'is_tourist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
