# Generated by Django 5.2.6 on 2025-11-19 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0003_accommodation_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='host',
            field=models.ForeignKey(limit_choices_to={'guide_approved': True, 'is_local_guide': True}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per night for the whole unit.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodation_booking.accommodation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(blank=True, limit_choices_to={'guide_approved': True, 'is_local_guide': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_tours_booked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tourist',
            field=models.ForeignKey(limit_choices_to={'is_tourist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
