# Generated by Django 5.2.6 on 2025-11-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0004_alter_accommodation_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
    ]
