# Generated by Django 5.2.6 on 2025-11-19 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0005_alter_accommodation_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_guides',
            field=models.ManyToManyField(blank=True, limit_choices_to={'guide_approved': True, 'is_local_guide': True}, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
