# Generated by Django 5.2.6 on 2025-11-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0007_booking_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tourist_valid_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_ids/'),
        ),
    ]
