# Generated by Django 5.2.6 on 2025-11-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0008_booking_tourist_valid_id_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='amenities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='offer_transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/rooms/'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='transport_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='transport_image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/transport/'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='photo',
            field=models.ImageField(default=1, upload_to='accommodations/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
