# Generated by Django 5.2.6 on 2025-11-28 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0009_accommodation_accommodation_type_and_more'),
        ('destinations_and_attractions', '0004_tourpackage_itinerary_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations', to='destinations_and_attractions.destination'),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
