# Generated by Django 5.2.6 on 2025-11-28 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0010_accommodation_destination_and_more'),
        ('destinations_and_attractions', '0004_tourpackage_itinerary_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='destinations_and_attractions.destination'),
        ),
    ]
