# Generated by Django 5.2.6 on 2025-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0011_booking_destination'),
        ('agency_management_module', '0005_agency_user_alter_touristguide_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_agency_guides',
            field=models.ManyToManyField(blank=True, related_name='assigned_bookings', to='agency_management_module.touristguide'),
        ),
    ]
