# Generated by Django 5.2.6 on 2025-12-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0012_booking_assigned_agency_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tourist_selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_selfies/'),
        ),
    ]
