# Generated by Django 5.2.6 on 2026-01-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0014_booking_balance_due_booking_down_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guide_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount Admin must send to Guide', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_payout_settled',
            field=models.BooleanField(default=False, help_text='Has Admin sent the money to the Guide?'),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='2% Commission for the App', max_digits=10),
        ),
    ]
