# Generated by Django 5.2.6 on 2026-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0015_booking_guide_payout_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending_Payment', 'Pending Payment'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending_Payment', max_length=50),
        ),
    ]
