# Generated by Django 5.2.6 on 2026-03-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0016_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meetup_instructions',
            field=models.TextField(blank=True, help_text='e.g., Look for the guide holding a blue LocaLynk umbrella.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='meetup_location',
            field=models.CharField(blank=True, help_text='Where the guide and tourist will meet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='meetup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
