# Generated by Django 5.2.6 on 2026-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0017_booking_meetup_instructions_booking_meetup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balance_paid_at',
            field=models.DateTimeField(blank=True, help_text='When the face-to-face balance was confirmed received', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='downpayment_paid_at',
            field=models.DateTimeField(blank=True, help_text='When the down payment was successfully processed online', null=True),
        ),
    ]
