# Generated by Django 5.2.6 on 2026-03-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0018_booking_balance_paid_at_booking_downpayment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_guest_names',
            field=models.JSONField(blank=True, default=list, help_text='List of additional guest names', null=True),
        ),
    ]
