# Generated by Django 5.2.6 on 2026-04-01 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0020_booking_tour_package'),
        ('agency_management_module', '0010_agency_available_days_agency_closing_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='agency_management_module.agency'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL),
        ),
    ]
