# Generated by Django 5.2.6 on 2026-04-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0021_accommodation_agency_alter_accommodation_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payout_channel',
            field=models.CharField(blank=True, choices=[('GCash', 'GCash'), ('Bank', 'Bank Transfer'), ('Maya', 'Maya'), ('Cash', 'Cash'), ('Other', 'Other')], help_text='How the payout was sent to provider.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin/staff who marked this payout as settled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_booking_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_reference_id',
            field=models.CharField(blank=True, help_text='GCash/bank transfer reference number.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_settled_at',
            field=models.DateTimeField(blank=True, help_text='When the payout was marked as settled.', null=True),
        ),
    ]
