# Generated by Django 5.2.6 on 2026-04-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0022_booking_payout_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingJourneyCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_key', models.CharField(max_length=80)),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('stop_index', models.PositiveIntegerField(default=0)),
                ('stop_name', models.CharField(max_length=255)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_type', models.CharField(blank=True, max_length=60, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('guide_remarks', models.TextField(blank=True, default='')),
                ('tourist_remarks', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_checkpoints', to='accommodation_booking.booking')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_checkpoints_checked', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_checkpoints_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_number', 'stop_index', 'id'],
                'constraints': [
                    models.UniqueConstraint(fields=('booking', 'stop_key'), name='unique_booking_journey_stop_key'),
                ],
            },
        ),
    ]
