# Generated by Django 5.2.6 on 2026-04-04

from django.db import migrations, models


def remove_legacy_self_messages(apps, schema_editor):
    Message = apps.get_model('communication', 'Message')
    Message.objects.filter(sender_id=models.F('receiver_id')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='message_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read', 'timestamp'], name='message_unread_idx'),
        ),
        migrations.RunPython(remove_legacy_self_messages, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(
                check=~models.Q(sender=models.F('receiver')),
                name='message_sender_receiver_different',
            ),
        ),
    ]
