# Generated by Django 5.2.6 on 2026-02-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations_and_attractions', '0005_destination_is_featured'),
        ('personalization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization',
            name='preferred_destinations',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='destinations_and_attractions.destination'),
        ),
    ]
