# Generated by Django 5.2.6 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0003_personalization_preferred_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalization',
            name='preferred_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='personalization',
            name='preferred_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='personalization',
            name='preferred_municipality',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
