# Generated by Django 5.2.6 on 2025-11-28 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_booking', '0011_booking_destination'),
        ('reviews_ratings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Guide Review'},
        ),
        migrations.AlterUniqueTogether(
            name='destinationreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='destinationreview',
            name='booking',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='destination_reviews', to='accommodation_booking.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='guide_reviews', to='accommodation_booking.booking'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='destinationreview',
            unique_together={('booking', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('booking', 'reviewer')},
        ),
    ]
