# Generated by Django 5.2.6 on 2025-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristguide',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['Mon', 'Wed', 'Fri'] or ['All']"),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='agency/guides/profiles/'),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='specific_available_dates',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['2025-12-25', '2026-01-01']"),
        ),
        migrations.AlterField(
            model_name='touristguide',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
