# Generated by Django 5.2.6 on 2025-11-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management_module', '0002_touristguide_available_days_touristguide_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristguide',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='touristguide',
            name='specific_available_dates',
        ),
    ]
