# Generated by Django 5.2.6 on 2025-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management_module', '0003_remove_touristguide_available_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristguide',
            name='guide_name',
        ),
        migrations.AddField(
            model_name='touristguide',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='touristguide',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
