# Generated by Django 5.2.6 on 2026-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management_module', '0005_agency_user_alter_touristguide_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristguide',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
