# Generated by Django 5.2.6 on 2026-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management_module', '0006_touristguide_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='down_payment_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Required downpayment percentage (e.g., 30 for 30%)', max_digits=5),
        ),
    ]
