# Generated by Django 5.2.6 on 2026-03-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management_module', '0007_agency_down_payment_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='agency',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
