# Generated by Django 5.2.6 on 2026-03-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management_module', '0008_remove_agency_is_approved_agency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agency/logos/'),
        ),
    ]
