# Generated by Django 5.2.6 on 2026-04-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management_module', '0009_agency_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text="e.g., ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']"),
        ),
        migrations.AddField(
            model_name='agency',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
