# Generated by Django 5.2.6 on 2025-11-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Booking', 'Booking Payment'), ('Fee', 'Service Fee')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(default='GCash', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Generic gateway transaction ID.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, help_text='Full response payload from the payment gateway.', null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
