# Generated by Django 5.2.6 on 2025-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gcash_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
