# Generated by Django 5.2.6 on 2025-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Booking', 'Booking Payment'), ('Fee', 'Service Fee'), ('YearlySubscription', 'Yearly Subscription')], max_length=50),
        ),
    ]
