# Generated by Django 5.2.6 on 2025-11-13 08:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_tourist', models.BooleanField(default=True)),
                ('is_local_guide', models.BooleanField(default=False)),
                ('guide_approved', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, help_text='e.g., City, Province', max_length=255, null=True)),
                ('guide_rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Average rating out of 5.0', max_digits=2, null=True)),
                ('experience_years', models.IntegerField(blank=True, default=0, null=True)),
                ('languages', models.JSONField(blank=True, default=list, help_text="List of languages spoken (e.g., ['English', 'Tagalog'])")),
                ('specialty', models.CharField(blank=True, help_text='Main guiding specialty (e.g., Mountain Guiding)', max_length=100, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=500.0, help_text='Base guide price (₱ 500/day)', max_digits=10)),
                ('solo_price_per_day', models.DecimalField(decimal_places=2, default=1500.0, help_text='Solo tourist price', max_digits=10)),
                ('multiple_additional_fee_per_head', models.DecimalField(decimal_places=2, default=100.0, help_text='Additional fee per head for groups', max_digits=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation_images_user/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_images_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='featured_places_user/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_places_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_guide_certificate', models.FileField(blank=True, null=True, upload_to='guide_docs/certs/')),
                ('proof_of_residency', models.FileField(blank=True, null=True, upload_to='guide_docs/residency/')),
                ('valid_id', models.FileField(blank=True, null=True, upload_to='guide_docs/id/')),
                ('nbi_clearance', models.FileField(blank=True, null=True, upload_to='guide_docs/nbi/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(help_text='The user associated with this guide application.', on_delete=django.db.models.deletion.CASCADE, related_name='guide_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
