# Generated by Django 5.2.6 on 2025-11-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text="List of days guide is available, e.g., ['Mon', 'Wed', 'Fri']"),
        ),
        migrations.AddField(
            model_name='user',
            name='tour_itinerary',
            field=models.TextField(blank=True, help_text="Standard itinerary description for the guide's tour.", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
