# Generated by Django 5.2.6 on 2025-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_user_available_days_user_tour_itinerary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
