# Generated by Django 5.2.6 on 2025-11-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_alter_user_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specific_available_dates',
            field=models.JSONField(blank=True, default=list, help_text="List of specific dates guide is available, e.g., ['2025-12-25', '2026-01-01']"),
        ),
    ]
