# Generated by Django 5.2.6 on 2025-11-25 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_user_specific_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guide_visible',
            field=models.BooleanField(default=False, help_text='True = Online (Visible to tourists), False = Offline (Hidden)'),
        ),
        migrations.AlterField(
            model_name='guideapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='multiple_additional_fee_per_head',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='solo_price_per_day',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='specific_available_dates',
            field=models.JSONField(blank=True, default=list, help_text="List of specific dates guide is available, e.g., ['2025-12-25']"),
        ),
        migrations.AlterField(
            model_name='user',
            name='tour_itinerary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
