# Generated by Django 5.2.6 on 2025-11-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_user_is_guide_visible_alter_guideapplication_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_kyc/'),
        ),
    ]
