# Generated by Django 5.2.6 on 2025-11-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0006_user_valid_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='guide_tier',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='guide_approved',
            field=models.BooleanField(default=True),
        ),
    ]
