# Generated by Django 5.2.6 on 2025-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0007_user_booking_count_user_guide_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guide_approved',
            field=models.BooleanField(default=False),
        ),
    ]
