# Generated by Django 5.2.6 on 2025-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0009_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
