# Generated by Django 5.2.6 on 2026-02-09 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0011_alter_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'guide')},
            },
        ),
    ]
