# Generated by Django 5.2.6 on 2026-02-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0012_favoriteguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scheduled_deletion_date',
            field=models.DateTimeField(blank=True, help_text='If set, this account is deactivated and will be deleted after this date.', null=True),
        ),
    ]
