# Generated by Django 5.2.6 on 2026-03-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0013_user_scheduled_deletion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the user requested deactivation. Triggers 30-day archive and 60-day deletion.', null=True),
        ),
    ]
