# Generated by Django 5.2.6 on 2026-03-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0014_user_deactivated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the user requested deactivation. Triggers 30-day archive and 365-day deletion.', null=True),
        ),
    ]
