# Generated by Django 5.2.6 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0015_alter_user_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_account_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_account_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_account_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_account_type',
            field=models.CharField(blank=True, choices=[('GCash', 'GCash'), ('Bank', 'Bank Transfer'), ('Maya', 'Maya'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
