# Generated by Django 5.2.6 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0016_user_payout_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_enabled',
            field=models.BooleanField(default=True, help_text='If false, user will not receive app activity emails.'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_enabled',
            field=models.BooleanField(default=True, help_text='If false, user will not receive app push notifications.'),
        ),
    ]